export function generateRandomUser(): { username: string; email: string; password: string } {
    const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
    const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
    const username = `${firstName.toLowerCase()}_${lastName.toLowerCase()}`;
    const email = `${username}@example.com`;
    const password = firstName.toLowerCase() + '123';

    return {username, email, password};
}

const firstNames = [
    'John',
    'Emily',
    'Michael',
    'Sophia',
    'William',
    'Emma',
    'Daniel',
    'Olivia',
    'Jacob',
    'Ava',
    'Matthew',
    'Isabella',
    'Andrew',
    'Mia',
    'Joseph',
    'Abigail',
    'David',
    'Emily',
    'Christopher',
    'Avery',
    'Joshua',
    'Amelia',
    'James',
    'Harper',
    'Benjamin',
    'Evelyn',
    'Ryan',
    'Ella',
    'Samuel',
    'Charlotte'
];

const lastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Miller',
    'Davis',
    'Garcia',
    'Rodriguez',
    'Wilson',
    'Martinez',
    'Anderson',
    'Taylor',
    'Thomas',
    'Hernandez',
    'Moore',
    'Martin',
    'Jackson',
    'Thompson',
    'White',
    'Lopez',
    'Lee',
    'Gonzalez',
    'Harris',
    'Clark',
    'Lewis',
    'Robinson',
    'Walker',
    'Perez',
    'Hall',
    'Young',
    'Allen',
    'Sanchez',
    'Wright',
    'King',
    'Scott',
    'Green',
    'Baker',
    'Adams',
    'Nelson',
    'Hill',
    'Ramirez',
    'Campbell',
    'Mitchell',
    'Roberts',
    'Carter',
    'Phillips']